//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerPath
    {
        public int CareerID { get; set; }
        public int CurrentPositionID { get; set; }
        public int TargetPositionID { get; set; }
        public Nullable<int> MinimumExperience { get; set; }
        public Nullable<decimal> MinimumPerformance { get; set; }
    }
}
