//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencies
    {
        public Competencies()
        {
            this.Employee_Competencies = new HashSet<Employee_Competencies>();
            this.Position_Requirements = new HashSet<Position_Requirements>();
            this.Trainings = new HashSet<Trainings>();
        }
    
        public int CompetencyID { get; set; }
        public string CompetencyName { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Employee_Competencies> Employee_Competencies { get; set; }
        public virtual ICollection<Position_Requirements> Position_Requirements { get; set; }
        public virtual ICollection<Trainings> Trainings { get; set; }
    }
}
