//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public Departments()
        {
            this.Departments1 = new HashSet<Departments>();
            this.Employees = new HashSet<Employees>();
            this.Positions = new HashSet<Positions>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ParentDepartmentID { get; set; }
    
        public virtual ICollection<Departments> Departments1 { get; set; }
        public virtual Departments Departments2 { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Positions> Positions { get; set; }
    }
}
