//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Trainings
    {
        public int EmployeeID { get; set; }
        public int TrainingID { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<bool> Certificate { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string Status { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Trainings Trainings { get; set; }
    }
}
