//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Competencies
    {
        public int EmployeeID { get; set; }
        public int CompetencyID { get; set; }
        public int CurrentLevel { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Competencies Competencies { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
