//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Employee_Competencies = new HashSet<Employee_Competencies>();
            this.Employee_Trainings = new HashSet<Employee_Trainings>();
            this.Employees1 = new HashSet<Employees>();
            this.Users = new HashSet<Users>();
        }
    
        public int EmployeeID { get; set; }
        public string SicilNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Phone { get; set; }
        public int DepartmentID { get; set; }
        public int PositionID { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<int> TotalExperienceYear { get; set; }
        public string EducationLevel { get; set; }
        public string ForeignLanguageLevel { get; set; }
        public string WorkStatus { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> CurrentCareerLvl { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual ICollection<Employee_Competencies> Employee_Competencies { get; set; }
        public virtual ICollection<Employee_Trainings> Employee_Trainings { get; set; }
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
