//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareerSystemEntities1 : DbContext
    {
        public CareerSystemEntities1()
            : base("name=CareerSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AIRecommendations> AIRecommendations { get; set; }
        public DbSet<CareerPath> CareerPath { get; set; }
        public DbSet<Competencies> Competencies { get; set; }
        public DbSet<Departments> Departments { get; set; }
        public DbSet<Employee_Competencies> Employee_Competencies { get; set; }
        public DbSet<Employee_Trainings> Employee_Trainings { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Performance> Performance { get; set; }
        public DbSet<Position_Requirements> Position_Requirements { get; set; }
        public DbSet<Positions> Positions { get; set; }
        public DbSet<Recommendation_Training> Recommendation_Training { get; set; }
        public DbSet<Trainings> Trainings { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
