//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int PerformanceID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime EvaluationDate { get; set; }
        public Nullable<decimal> PerformanceScore { get; set; }
        public string Evaluator { get; set; }
    }
}
