//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positions
    {
        public Positions()
        {
            this.Employees = new HashSet<Employees>();
            this.Position_Requirements = new HashSet<Position_Requirements>();
        }
    
        public int PositionID { get; set; }
        public string PositionName { get; set; }
        public int DepartmentID { get; set; }
        public int CareerLevel { get; set; }
        public int MinimumExperience { get; set; }
        public string EducationLevel { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Position_Requirements> Position_Requirements { get; set; }
    }
}
