//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position_Requirements
    {
        public int PositionID { get; set; }
        public int CompetencyID { get; set; }
        public int RequiredLevel { get; set; }
        public Nullable<int> MinimumExperience { get; set; }
    
        public virtual Competencies Competencies { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
