//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerManagamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        public Trainings()
        {
            this.Employee_Trainings = new HashSet<Employee_Trainings>();
        }
    
        public int TrainingID { get; set; }
        public string TrainingName { get; set; }
        public int CompetencyID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Competencies Competencies { get; set; }
        public virtual ICollection<Employee_Trainings> Employee_Trainings { get; set; }
    }
}
